import React, { useState, useRef, useEffect } from 'react';
import { AlertTriangle, Sparkles, AlignJustify, Loader2 } from 'lucide-react';

/**
 * AIInputField Component - Fully Reusable AI-Driven Input with Suggestions
 * 
 * A comprehensive, generic input component with AI-powered autocomplete suggestions.
 * Supports dual-mode operation (auto-generate vs manual entry), intelligent suggestions,
 * conflict detection, keyboard navigation, and full accessibility.
 * 
 * @features
 * - ✅ Dual Mode: Auto-generate or Manual entry
 * - ✅ AI-Powered Suggestions: Grouped by type (AI-driven, System-defined, Custom)
 * - ✅ Smart Conflict Detection: Detects duplicates with intelligent alternatives
 * - ✅ Keyboard Navigation: Full arrow key + Enter + Escape support
 * - ✅ Debounced Search: Optional async search with loading states
 * - ✅ Text Highlighting: Visual search match highlighting in suggestions
 * - ✅ Accessibility: ARIA labels, roles, focus management
 * - ✅ Responsive Dropdown: Auto-positioning, max-height, smooth scrolling
 * - ✅ Copy Functionality: Copy auto-generated values to clipboard
 * - ✅ Loading States: Spinner for async operations
 * - ✅ Error States: Visual feedback for conflicts/errors
 * - ✅ Customizable: Extensive prop configuration for any use case
 * 
 * @useCases
 * - SKU Code Generation
 * - Product Name Autocomplete
 * - Customer/Vendor Search
 * - HSN/SAC Code Lookup
 * - Category Selection
 * - Any AI-driven input field
 * 
 * @example Basic Usage
 * ```tsx
 * <AIInputField
 *   label="Product SKU"
 *   mode="manual"
 *   value={sku}
 *   onChange={setSku}
 *   suggestions={[
 *     { value: 'SKU-2024-001', type: 'ai', label: 'Based on pattern' },
 *     { value: 'SKU-2024-002', type: 'system' }
 *   ]}
 * />
 * ```
 * 
 * @example Dual Mode with Auto-Generate
 * ```tsx
 * <AIInputField
 *   label="SKU Code"
 *   mode={skuMode}
 *   value={skuValue}
 *   autoGeneratedValue="AUTO-SKU-12345"
 *   onModeChange={setSkuMode}
 *   onChange={setSkuValue}
 *   enableModeToggle
 *   autoModeLabel="Auto-generate"
 *   manualModeLabel="Enter manually"
 * />
 * ```
 * 
 * @example With Conflict Detection
 * ```tsx
 * <AIInputField
 *   label="Customer Code"
 *   value={customerCode}
 *   onChange={setCustomerCode}
 *   hasConflict={isDuplicate}
 *   conflictValue="CUST-001"
 *   conflictMessage="This customer code already exists"
 *   conflictSuggestions={{
 *     ai: { value: 'CUST-001-V2', confidence: 95, reason: 'Version suffix' },
 *     pattern: { value: 'CUST-002', confidence: 92, reason: 'Sequential' }
 *   }}
 * />
 * ```
 * 
 * @example Async Search
 * ```tsx
 * <AIInputField
 *   label="Product Name"
 *   value={productName}
 *   onChange={setProductName}
 *   onSearch={async (query) => {
 *     const results = await fetchProducts(query);
 *     return results.map(p => ({ value: p.name, type: 'system' }));
 *   }}
 *   debounceMs={300}
 * />
 * ```
 */

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

export type SuggestionType = 'ai' | 'system' | 'custom';
export type InputMode = 'auto' | 'manual';

export interface Suggestion {
  /** The suggestion value (what gets inserted into the input) */
  value: string;
  
  /** Type of suggestion (determines grouping and styling) */
  type: SuggestionType;
  
  /** Optional descriptive label shown beside the value */
  label?: string;
  
  /** Optional metadata (e.g., "Based on pattern", "Most common") */
  metadata?: string;
  
  /** Optional confidence score (0-100) for AI suggestions */
  confidence?: number;
}

export interface ConflictSuggestion {
  /** Suggested alternative value */
  value: string;
  
  /** Confidence score (0-100) */
  confidence?: number;
  
  /** Reason for this suggestion */
  reason?: string;
}

export interface ConflictSuggestions {
  /** AI-generated suggestion */
  ai?: ConflictSuggestion;
  
  /** Pattern-based suggestion */
  pattern?: ConflictSuggestion;
  
  /** Custom suggestions */
  custom?: ConflictSuggestion[];
}

export interface AIInputFieldProps {
  // ========== CORE PROPERTIES ==========
  
  /** Current input value */
  value: string;
  
  /** Value change handler */
  onChange: (value: string) => void;
  
  /** Field label */
  label?: string;
  
  /** Required field indicator */
  required?: boolean;
  
  /** Disabled state */
  disabled?: boolean;
  
  /** Additional CSS classes */
  className?: string;
  
  // ========== MODE CONFIGURATION ==========
  
  /** Current mode: 'auto' (auto-generate) or 'manual' (user input) */
  mode?: InputMode;
  
  /** Mode change handler */
  onModeChange?: (mode: InputMode) => void;
  
  /** Enable dual-mode toggle (radio buttons) */
  enableModeToggle?: boolean;
  
  /** Label for auto-generate mode */
  autoModeLabel?: string;
  
  /** Label for manual entry mode */
  manualModeLabel?: string;
  
  /** Auto-generated value (shown in auto mode) */
  autoGeneratedValue?: string;
  
  /** Enable copy button in auto mode */
  enableCopyButton?: boolean;
  
  // ========== PLACEHOLDER CONFIGURATION ==========
  
  /** Placeholder text (string or mode-specific object) */
  placeholder?: string | {
    auto?: string;
    manual?: string;
  };
  
  // ========== SUGGESTIONS CONFIGURATION ==========
  
  /** Array of suggestions to display */
  suggestions?: Suggestion[];
  
  /** Callback when a suggestion is selected */
  onSuggestionSelect?: (value: string, suggestion: Suggestion) => void;
  
  /** Enable suggestion filtering based on input */
  enableSuggestionFiltering?: boolean;
  
  /** Custom filter function for suggestions */
  filterSuggestions?: (suggestions: Suggestion[], query: string) => Suggestion[];
  
  /** Async search function (returns suggestions) */
  onSearch?: (query: string) => Promise<Suggestion[]>;
  
  /** Debounce delay for async search (ms) */
  debounceMs?: number;
  
  /** Minimum characters to trigger search */
  minSearchLength?: number;
  
  /** Loading state (for async operations) */
  isLoading?: boolean;
  
  /** Empty state message when no suggestions found */
  emptyMessage?: string;
  
  // ========== CONFLICT/ERROR CONFIGURATION ==========
  
  /** Whether input has a conflict (duplicate/error) */
  hasConflict?: boolean;
  
  /** The conflicting value (e.g., existing SKU) */
  conflictValue?: string;
  
  /** Custom conflict error message */
  conflictMessage?: string;
  
  /** Smart suggestions to resolve conflict */
  conflictSuggestions?: ConflictSuggestions;
  
  /** Show conflict suggestions in callout (below input) */
  showConflictCallout?: boolean;
  
  /** Validation function (returns true if conflict exists) */
  onValidate?: (value: string) => boolean | Promise<boolean>;
  
  // ========== DROPDOWN BEHAVIOR ==========
  
  /** Maximum height of dropdown (CSS value) */
  dropdownMaxHeight?: string;
  
  /** Show dropdown on focus */
  showOnFocus?: boolean;
  
  /** Custom dropdown positioning */
  dropdownPosition?: 'bottom' | 'top' | 'auto';
  
  /** Z-index for dropdown */
  dropdownZIndex?: number;
  
  // ========== SUGGESTION GROUPING ==========
  
  /** Custom group labels */
  groupLabels?: {
    ai?: string;
    system?: string;
    custom?: string;
  };
  
  /** Hide specific groups */
  hideGroups?: SuggestionType[];
  
  // ========== VISUAL CUSTOMIZATION ==========
  
  /** Enable text highlighting in suggestions */
  enableHighlighting?: boolean;
  
  /** Custom icon for AI suggestions */
  aiIcon?: React.ReactNode;
  
  /** Custom icon for system suggestions */
  systemIcon?: React.ReactNode;
  
  /** Custom icon for conflict/error */
  conflictIcon?: React.ReactNode;
  
  // ========== ACCESSIBILITY ==========
  
  /** ARIA label */
  ariaLabel?: string;
  
  /** ARIA description */
  ariaDescription?: string;
  
  /** Custom input ID */
  inputId?: string;
  
  /** Autocomplete attribute */
  autoComplete?: string;
  
  // ========== ADVANCED ==========
  
  /** Custom render function for suggestion items */
  renderSuggestion?: (suggestion: Suggestion, isHighlighted: boolean) => React.ReactNode;
  
  /** Callback when dropdown opens */
  onDropdownOpen?: () => void;
  
  /** Callback when dropdown closes */
  onDropdownClose?: () => void;
  
  /** Custom input ref */
  inputRef?: React.RefObject<HTMLInputElement>;
}

// ============================================================================
// COMPONENT
// ============================================================================

export function AIInputField({
  // Core
  value,
  onChange,
  label,
  required = false,
  disabled = false,
  className = '',
  
  // Mode
  mode = 'manual',
  onModeChange,
  enableModeToggle = false,
  autoModeLabel = 'Auto-generate',
  manualModeLabel = 'Enter manually',
  autoGeneratedValue = '',
  enableCopyButton = true,
  
  // Placeholder
  placeholder = {
    auto: 'Value will be auto-generated',
    manual: 'Enter value manually'
  },
  
  // Suggestions
  suggestions = [],
  onSuggestionSelect,
  enableSuggestionFiltering = true,
  filterSuggestions,
  onSearch,
  debounceMs = 300,
  minSearchLength = 1,
  isLoading = false,
  emptyMessage = 'No suggestions found',
  
  // Conflict/Error
  hasConflict = false,
  conflictValue,
  conflictMessage = 'This value already exists',
  conflictSuggestions,
  showConflictCallout = true,
  onValidate,
  
  // Dropdown
  dropdownMaxHeight = '320px',
  showOnFocus = true,
  dropdownPosition = 'bottom',
  dropdownZIndex = 50,
  
  // Grouping
  groupLabels = {
    ai: 'AI-driven suggestions',
    system: 'System-Defined',
    custom: 'Suggestions'
  },
  hideGroups = [],
  
  // Visual
  enableHighlighting = true,
  aiIcon,
  systemIcon,
  conflictIcon,
  
  // Accessibility
  ariaLabel,
  ariaDescription,
  inputId,
  autoComplete = 'off',
  
  // Advanced
  renderSuggestion,
  onDropdownOpen,
  onDropdownClose,
  inputRef: externalInputRef
}: AIInputFieldProps) {
  // ========== STATE ==========
  const [showDropdown, setShowDropdown] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const [asyncSuggestions, setAsyncSuggestions] = useState<Suggestion[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  
  // ========== REFS ==========
  const containerRef = useRef<HTMLDivElement>(null);
  const internalInputRef = useRef<HTMLInputElement>(null);
  const inputRef = externalInputRef || internalInputRef;
  const debounceTimerRef = useRef<NodeJS.Timeout>();
  
  // ========== COMPUTED VALUES ==========
  
  // Get placeholder text based on mode
  const placeholderText = typeof placeholder === 'string' 
    ? placeholder 
    : mode === 'auto' 
      ? placeholder.auto 
      : placeholder.manual;
  
  // Merge static and async suggestions
  const allSuggestions = [...suggestions, ...asyncSuggestions];
  
  // Filter suggestions based on input value
  const filteredSuggestions = enableSuggestionFiltering && mode === 'manual' && value.trim()
    ? (filterSuggestions 
        ? filterSuggestions(allSuggestions, value)
        : allSuggestions.filter(s => 
            s.value.toLowerCase().includes(value.toLowerCase())
          ))
    : allSuggestions;
  
  // Group suggestions by type
  const aiSuggestions = filteredSuggestions.filter(s => s.type === 'ai' && !hideGroups.includes('ai'));
  const systemSuggestions = filteredSuggestions.filter(s => s.type === 'system' && !hideGroups.includes('system'));
  const customSuggestions = filteredSuggestions.filter(s => s.type === 'custom' && !hideGroups.includes('custom'));
  
  const hasAnySuggestions = aiSuggestions.length > 0 || systemSuggestions.length > 0 || customSuggestions.length > 0;
  
  // Calculate default conflict suggestions
  const defaultConflictSuggestions: ConflictSuggestions = conflictSuggestions || {
    ai: {
      value: value ? `${value}-V2` : '',
      confidence: 95,
      reason: 'Version suffix'
    },
    pattern: {
      value: value.match(/^(.+?)[-_]?(\d+)$/) 
        ? value.replace(/(\d+)$/, (match) => String(parseInt(match) + 1).padStart(3, '0'))
        : `${value}-002`,
      confidence: 92,
      reason: 'Sequential numbering'
    }
  };
  
  // ========== ASYNC SEARCH ==========
  
  useEffect(() => {
    if (!onSearch || mode === 'auto') return;
    
    // Clear previous timer
    if (debounceTimerRef.current) {
      clearTimeout(debounceTimerRef.current);
    }
    
    // Only search if minimum length met
    if (value.length < minSearchLength) {
      setAsyncSuggestions([]);
      setIsSearching(false);
      return;
    }
    
    // Set loading state
    setIsSearching(true);
    
    // Debounced search
    debounceTimerRef.current = setTimeout(async () => {
      try {
        const results = await onSearch(value);
        setAsyncSuggestions(results);
      } catch (error) {
        console.error('Search failed:', error);
        setAsyncSuggestions([]);
      } finally {
        setIsSearching(false);
      }
    }, debounceMs);
    
    return () => {
      if (debounceTimerRef.current) {
        clearTimeout(debounceTimerRef.current);
      }
    };
  }, [value, onSearch, debounceMs, minSearchLength, mode]);
  
  // ========== DROPDOWN CONTROL ==========
  
  const openDropdown = () => {
    if (!showDropdown) {
      setShowDropdown(true);
      onDropdownOpen?.();
    }
  };
  
  const closeDropdown = () => {
    if (showDropdown) {
      setShowDropdown(false);
      setHighlightedIndex(-1);
      onDropdownClose?.();
    }
  };
  
  // ========== CLICK OUTSIDE HANDLER ==========
  
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        closeDropdown();
      }
    };
    
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showDropdown]);
  
  // ========== SUGGESTION SELECTION ==========
  
  const handleSuggestionClick = (suggestion: Suggestion) => {
    onChange(suggestion.value);
    onSuggestionSelect?.(suggestion.value, suggestion);
    closeDropdown();
  };
  
  // ========== KEYBOARD NAVIGATION ==========
  
  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (mode === 'manual' && hasAnySuggestions && showDropdown) {
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        setHighlightedIndex(prev => 
          prev < filteredSuggestions.length - 1 ? prev + 1 : prev
        );
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        setHighlightedIndex(prev => prev > 0 ? prev - 1 : -1);
      } else if (e.key === 'Enter' && highlightedIndex >= 0) {
        e.preventDefault();
        const selectedSuggestion = filteredSuggestions[highlightedIndex];
        handleSuggestionClick(selectedSuggestion);
      } else if (e.key === 'Escape') {
        e.preventDefault();
        closeDropdown();
      }
    }
  };
  
  // ========== COPY TO CLIPBOARD ==========
  
  const handleCopy = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    e.stopPropagation();
    
    try {
      const textArea = document.createElement('textarea');
      textArea.value = autoGeneratedValue;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      document.execCommand('copy');
      textArea.remove();
      
      // Visual feedback
      const btn = e.currentTarget;
      const originalTitle = btn.title;
      btn.title = 'Copied!';
      btn.classList.add('bg-green-100');
      setTimeout(() => {
        btn.title = originalTitle;
        btn.classList.remove('bg-green-100');
      }, 1500);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };
  
  // ========== TEXT HIGHLIGHTING ==========
  
  const renderHighlightedText = (text: string, searchTerm: string) => {
    if (!enableHighlighting || !searchTerm) return text;
    
    const lowerText = text.toLowerCase();
    const lowerSearch = searchTerm.toLowerCase();
    const matchIndex = lowerText.indexOf(lowerSearch);
    
    if (matchIndex >= 0) {
      return (
        <>
          {text.substring(0, matchIndex)}
          <span className="font-semibold bg-yellow-100">
            {text.substring(matchIndex, matchIndex + searchTerm.length)}
          </span>
          {text.substring(matchIndex + searchTerm.length)}
        </>
      );
    }
    return text;
  };
  
  // ========== DEFAULT ICONS ==========
  
  const defaultAiIcon = <Sparkles className="w-4 h-4 text-purple-600 flex-shrink-0" />;
  const defaultSystemIcon = <AlignJustify className="w-4 h-4 text-gray-400 flex-shrink-0" />;
  const defaultConflictIcon = <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0" />;
  
  const aiIconElement = aiIcon || defaultAiIcon;
  const systemIconElement = systemIcon || defaultSystemIcon;
  const conflictIconElement = conflictIcon || defaultConflictIcon;
  
  // ========== RENDER SUGGESTION ITEM ==========
  
  const renderSuggestionItem = (suggestion: Suggestion, index: number, isHighlighted: boolean) => {
    if (renderSuggestion) {
      return renderSuggestion(suggestion, isHighlighted);
    }
    
    const icon = suggestion.type === 'ai' ? aiIconElement : systemIconElement;
    const highlightClass = isHighlighted 
      ? (suggestion.type === 'ai' ? 'bg-purple-50' : 'bg-blue-50')
      : 'hover:bg-gray-50';
    
    return (
      <div
        key={`${suggestion.type}-${suggestion.value}-${index}`}
        onClick={() => handleSuggestionClick(suggestion)}
        onMouseEnter={() => setHighlightedIndex(index)}
        className={`px-3 py-2.5 cursor-pointer transition-colors border-b border-gray-50 last:border-b-0 ${highlightClass}`}
        role="option"
        aria-selected={isHighlighted}
      >
        <div className="flex items-center gap-2">
          {icon}
          <span className="text-sm text-gray-900 font-mono flex-1">
            {renderHighlightedText(suggestion.value, value)}
          </span>
          {(suggestion.label || suggestion.metadata) && (
            <span className="text-xs text-gray-500">
              {suggestion.label || suggestion.metadata}
            </span>
          )}
          {suggestion.confidence && (
            <span className="text-xs text-purple-600 font-medium">
              {suggestion.confidence}%
            </span>
          )}
        </div>
      </div>
    );
  };
  
  // ========== RENDER ==========
  
  return (
    <div className={className} ref={containerRef}>
      {/* Label and Mode Toggle */}
      <div className="flex items-center gap-3 mb-2">
        <label 
          htmlFor={inputId} 
          className="text-sm text-gray-700 whitespace-nowrap"
          style={{ fontFamily: 'Poppins, sans-serif' }}
        >
          {label} {required && <span className="text-red-500">*</span>}
        </label>
        
        {enableModeToggle && onModeChange && (
          <div className="flex items-center gap-4">
            {/* Auto Generate Radio */}
            <label className="flex items-center gap-1.5 cursor-pointer">
              <input
                type="radio"
                name={`${inputId || label}-mode`}
                value="auto"
                checked={mode === 'auto'}
                onChange={() => {
                  onModeChange('auto');
                  closeDropdown();
                }}
                disabled={disabled}
                className="w-4 h-4 text-[#5C1F3D] focus:ring-[#5C1F3D]"
              />
              <span className="text-sm text-gray-700" style={{ fontFamily: 'Poppins, sans-serif' }}>
                {autoModeLabel}
              </span>
            </label>
            
            {/* Manual Entry Radio */}
            <label className="flex items-center gap-1.5 cursor-pointer">
              <input
                type="radio"
                name={`${inputId || label}-mode`}
                value="manual"
                checked={mode === 'manual'}
                onChange={() => onModeChange('manual')}
                disabled={disabled}
                className="w-4 h-4 text-[#5C1F3D] focus:ring-[#5C1F3D]"
              />
              <span className="text-sm text-gray-700" style={{ fontFamily: 'Poppins, sans-serif' }}>
                {manualModeLabel}
              </span>
            </label>
          </div>
        )}
      </div>
      
      {/* Input Field Container */}
      <div className="relative">
        <div 
          className={mode === 'auto' ? 'pointer-events-none' : ''}
          style={mode === 'auto' ? { pointerEvents: 'none' } : {}}
        >
          <input
            ref={inputRef}
            id={inputId}
            type="text"
            placeholder={placeholderText}
            disabled={mode === 'auto' || disabled}
            value={mode === 'auto' ? autoGeneratedValue : value}
            onChange={(e) => {
              onChange(e.target.value);
              if (mode === 'manual') {
                openDropdown();
                setHighlightedIndex(-1);
              }
            }}
            onKeyDown={handleKeyDown}
            onFocus={() => {
              if (mode === 'manual' && showOnFocus && value.trim()) {
                openDropdown();
              }
            }}
            autoComplete={autoComplete}
            aria-label={ariaLabel || label}
            aria-description={ariaDescription}
            aria-invalid={hasConflict}
            aria-autocomplete="list"
            aria-controls={showDropdown ? `${inputId}-dropdown` : undefined}
            aria-expanded={showDropdown}
            className={`w-full px-3 py-2 border rounded-[3px] text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:border-transparent bg-white transition-colors ${
              mode === 'manual' && hasConflict
                ? 'border-red-500 focus:ring-red-500'
                : 'border-gray-300 focus:ring-[#5C1F3D]'
            } ${mode === 'auto' ? 'bg-gray-50 text-gray-500' : ''}`}
            style={{ 
              height: '33px',
              fontFamily: 'Poppins, sans-serif'
            }}
          />
        </div>
        
        {/* Loading Spinner */}
        {(isLoading || isSearching) && mode === 'manual' && (
          <div className="absolute right-3 top-1/2 -translate-y-1/2">
            <Loader2 className="w-4 h-4 text-gray-400 animate-spin" />
          </div>
        )}
        
        {/* Copy Button (Auto Mode) */}
        {mode === 'auto' && autoGeneratedValue && enableCopyButton && (
          <button
            onClick={handleCopy}
            title="Copy to clipboard"
            className="absolute right-2 top-1/2 -translate-y-1/2 p-1.5 hover:bg-gray-100 rounded transition-colors pointer-events-auto"
          >
            <svg 
              className="w-4 h-4 text-gray-600" 
              fill="none" 
              stroke="currentColor" 
              viewBox="0 0 24 24"
            >
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </button>
        )}
        
        {/* Suggestions Dropdown */}
        {mode === 'manual' && showDropdown && (
          <div 
            id={`${inputId}-dropdown`}
            className="absolute top-full left-0 right-0 mt-1 bg-white border border-gray-300 rounded-[3px] shadow-lg overflow-y-auto"
            style={{ 
              maxHeight: dropdownMaxHeight,
              zIndex: dropdownZIndex
            }}
            role="listbox"
            aria-label={`${label} suggestions`}
          >
            {/* Conflict Banner */}
            {hasConflict && (
              <div className="px-3 py-2.5 bg-red-50 border-b border-red-200 flex items-start gap-2">
                {conflictIconElement}
                <div className="flex-1">
                  <p className="text-xs text-red-800 font-medium">{conflictMessage}</p>
                  {conflictValue && (
                    <p className="text-xs text-red-600 mt-0.5">
                      Conflicts with: <code className="font-mono">{conflictValue}</code>
                    </p>
                  )}
                </div>
              </div>
            )}
            
            {/* AI Suggestions Group */}
            {aiSuggestions.length > 0 && (
              <>
                <div className="px-3 py-1.5 text-xs font-medium text-purple-700 bg-purple-50 border-b border-purple-100 flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5" />
                  {groupLabels.ai}
                </div>
                {aiSuggestions.map((suggestion, idx) => 
                  renderSuggestionItem(suggestion, idx, highlightedIndex === idx)
                )}
              </>
            )}
            
            {/* System Suggestions Group */}
            {systemSuggestions.length > 0 && (
              <>
                <div className="px-3 py-1.5 text-xs font-medium text-gray-500 bg-gray-50 border-b border-gray-100 flex items-center gap-1.5">
                  <AlignJustify className="w-3.5 h-3.5" />
                  {groupLabels.system}
                </div>
                {systemSuggestions.map((suggestion, idx) => {
                  const adjustedIdx = idx + aiSuggestions.length;
                  return renderSuggestionItem(suggestion, adjustedIdx, highlightedIndex === adjustedIdx);
                })}
              </>
            )}
            
            {/* Custom Suggestions Group */}
            {customSuggestions.length > 0 && (
              <>
                <div className="px-3 py-1.5 text-xs font-medium text-gray-500 bg-gray-50 border-b border-gray-100">
                  {groupLabels.custom}
                </div>
                {customSuggestions.map((suggestion, idx) => {
                  const adjustedIdx = idx + aiSuggestions.length + systemSuggestions.length;
                  return renderSuggestionItem(suggestion, adjustedIdx, highlightedIndex === adjustedIdx);
                })}
              </>
            )}
            
            {/* Empty State */}
            {!hasAnySuggestions && !isSearching && !isLoading && (
              <div className="px-4 py-6 text-center text-sm text-gray-500">
                {emptyMessage}
              </div>
            )}
            
            {/* Loading State */}
            {(isSearching || isLoading) && (
              <div className="px-4 py-6 flex items-center justify-center gap-2">
                <Loader2 className="w-4 h-4 text-gray-400 animate-spin" />
                <span className="text-sm text-gray-500">Searching...</span>
              </div>
            )}
          </div>
        )}
      </div>
      
      {/* Conflict Error Message (Below Input) */}
      {hasConflict && mode === 'manual' && !showDropdown && (
        <div className="mt-2 flex items-start gap-2">
          {conflictIconElement}
          <div className="flex-1">
            <p className="text-xs text-red-600">{conflictMessage}</p>
            {conflictValue && (
              <div className="flex items-center gap-2 mt-1">
                <code className="text-xs font-mono text-red-700 bg-red-50 px-2 py-0.5 rounded">
                  {conflictValue}
                </code>
                <button
                  onClick={() => openDropdown()}
                  className="text-xs text-[#5C1F3D] hover:text-[#4a1831] underline font-medium"
                >
                  See suggestions
                </button>
              </div>
            )}
          </div>
        </div>
      )}
      
      {/* Conflict Suggestions Callout */}
      {hasConflict && mode === 'manual' && showConflictCallout && defaultConflictSuggestions && (
        <div className="mt-2 p-3 bg-purple-50 border-l-4 border-[#5C1F3D] rounded-r-[3px]">
          <div className="flex items-start gap-2">
            <Sparkles className="w-4 h-4 text-[#5C1F3D] mt-0.5 flex-shrink-0" />
            <div className="flex-1">
              <p className="text-xs text-gray-900 mb-1">
                <span className="font-medium">{conflictMessage}</span>
              </p>
              <div className="mt-2">
                <p className="text-xs font-medium text-[#5C1F3D] mb-2">AI Suggestions</p>
                <div className="space-y-2">
                  {/* AI Suggestion */}
                  {defaultConflictSuggestions.ai && (
                    <div className="flex items-center gap-2">
                      <span className="px-1.5 py-0.5 text-xs rounded flex-shrink-0 bg-purple-100 text-purple-700 border border-purple-200">
                        AI
                      </span>
                      <span className="text-xs text-gray-600 flex-shrink-0">
                        {defaultConflictSuggestions.ai.confidence}%: {defaultConflictSuggestions.ai.reason}
                      </span>
                      <code className="flex-1 px-2 py-1 bg-white border border-gray-200 rounded text-xs font-mono text-gray-900">
                        {defaultConflictSuggestions.ai.value}
                      </code>
                      <button
                        onClick={() => {
                          onChange(defaultConflictSuggestions.ai!.value);
                          closeDropdown();
                        }}
                        className="px-3 py-1 text-xs bg-[#5C1F3D] text-white rounded-[3px] hover:bg-[#4a1831] transition-colors whitespace-nowrap flex-shrink-0"
                      >
                        Use this
                      </button>
                    </div>
                  )}
                  
                  {/* Pattern Suggestion */}
                  {defaultConflictSuggestions.pattern && (
                    <div className="flex items-center gap-2">
                      <span className="px-1.5 py-0.5 text-xs rounded flex-shrink-0 bg-blue-100 text-blue-700 border border-blue-200">
                        Pattern
                      </span>
                      <span className="text-xs text-gray-600 flex-shrink-0">
                        {defaultConflictSuggestions.pattern.confidence}%: {defaultConflictSuggestions.pattern.reason}
                      </span>
                      <code className="flex-1 px-2 py-1 bg-white border border-gray-200 rounded text-xs font-mono text-gray-900">
                        {defaultConflictSuggestions.pattern.value}
                      </code>
                      <button
                        onClick={() => {
                          onChange(defaultConflictSuggestions.pattern!.value);
                          closeDropdown();
                        }}
                        className="px-3 py-1 text-xs bg-[#5C1F3D] text-white rounded-[3px] hover:bg-[#4a1831] transition-colors whitespace-nowrap flex-shrink-0"
                      >
                        Use this
                      </button>
                    </div>
                  )}
                  
                  {/* Custom Suggestions */}
                  {defaultConflictSuggestions.custom?.map((customSugg, idx) => (
                    <div key={idx} className="flex items-center gap-2">
                      <span className="px-1.5 py-0.5 text-xs rounded flex-shrink-0 bg-gray-100 text-gray-700 border border-gray-200">
                        Custom
                      </span>
                      <span className="text-xs text-gray-600 flex-shrink-0">
                        {customSugg.confidence}%: {customSugg.reason}
                      </span>
                      <code className="flex-1 px-2 py-1 bg-white border border-gray-200 rounded text-xs font-mono text-gray-900">
                        {customSugg.value}
                      </code>
                      <button
                        onClick={() => {
                          onChange(customSugg.value);
                          closeDropdown();
                        }}
                        className="px-3 py-1 text-xs bg-[#5C1F3D] text-white rounded-[3px] hover:bg-[#4a1831] transition-colors whitespace-nowrap flex-shrink-0"
                      >
                        Use this
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
