import React, { useState, useRef, useEffect } from 'react';
import { AlertTriangle, Sparkles, AlignJustify } from 'lucide-react';

/**
 * BundleCodeInput Component
 * 
 * A comprehensive Bundle Code input component with dual modes:
 * - Auto Generate: Automatically generates bundle codes based on system patterns
 * - Manual Entry: Allows manual input with intelligent autocomplete suggestions
 * 
 * Features:
 * - Dual mode selection (Auto Generate / Manual Entry)
 * - Auto-generated bundle code display with copy functionality
 * - Intelligent autocomplete with AI-driven and system-defined suggestions
 * - Keyboard navigation support (Arrow keys, Enter, Escape)
 * - Duplicate code detection and smart suggestions
 * - Text highlighting in suggestions for better UX
 * - Grouped suggestions (AI-driven vs System-defined)
 * - Visual feedback for duplicate codes
 * - Accessibility support with proper ARIA labels
 * 
 * @example
 * ```tsx
 * <BundleCodeInput
 *   mode="manual"
 *   value="BDL-2024-001"
 *   autoGeneratedValue="BDL-AUTO-12345"
 *   onModeChange={(mode) => setMode(mode)}
 *   onChange={(value) => setBundleCode(value)}
 *   suggestions={[
 *     { value: 'BDL-2024-001', type: 'ai', reason: 'Based on pattern' },
 *     { value: 'BDL-2024-002', type: 'match', reason: 'Sequential' }
 *   ]}
 *   isDuplicate={false}
 *   onSuggestionSelect={(value) => console.log('Selected:', value)}
 *   required
 * />
 * ```
 */

export interface BundleCodeSuggestion {
  value: string;
  type: 'ai' | 'match';
  reason?: string;
}

export interface BundleCodeInputProps {
  // Core Values
  mode: 'auto' | 'manual';
  value: string;
  autoGeneratedValue?: string;
  
  // Change Handlers
  onModeChange: (mode: 'auto' | 'manual') => void;
  onChange: (value: string) => void;
  
  // Suggestions
  suggestions?: BundleCodeSuggestion[];
  onSuggestionSelect?: (value: string) => void;
  
  // Duplicate Detection
  isDuplicate?: boolean;
  duplicateSuggestions?: {
    aiSuggestion: string;
    patternSuggestion: string;
    aiConfidence?: number;
    patternConfidence?: number;
  };
  onValidate?: (value: string) => boolean; // Returns true if duplicate
  existingCodes?: string[]; // List of all bundle codes in inventory
  duplicateErrorMessage?: string; // Custom error message
  conflictingCode?: string; // The exact code that conflicts
  
  // Optional Configuration
  required?: boolean;
  disabled?: boolean;
  placeholder?: {
    auto?: string;
    manual?: string;
  };
  className?: string;
  
  // Labels
  label?: string;
  autoModeLabel?: string;
  manualModeLabel?: string;
}

export function BundleCodeInput({
  mode,
  value,
  autoGeneratedValue = '',
  onModeChange,
  onChange,
  suggestions = [],
  onSuggestionSelect,
  isDuplicate = false,
  duplicateSuggestions,
  onValidate,
  existingCodes,
  duplicateErrorMessage,
  conflictingCode,
  required = false,
  disabled = false,
  placeholder = {
    auto: 'Bundle code will be auto-generated',
    manual: 'Enter bundle code manually'
  },
  className = '',
  label = 'Bundle Code',
  autoModeLabel = 'Auto Generate',
  manualModeLabel = 'Manual Entry'
}: BundleCodeInputProps) {
  // Internal state for dropdown and keyboard navigation
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const bundleCodeInputRef = useRef<HTMLDivElement>(null);

  // Filter suggestions based on current input
  const filteredSuggestions = mode === 'manual' && value.trim()
    ? suggestions.filter(s => 
        s.value.toLowerCase().includes(value.toLowerCase())
      )
    : suggestions;

  // Handle clicks outside to close dropdown
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (bundleCodeInputRef.current && !bundleCodeInputRef.current.contains(event.target as Node)) {
        setShowSuggestions(false);
        setHighlightedIndex(-1);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Handle suggestion selection
  const handleSuggestionClick = (suggestionValue: string) => {
    onChange(suggestionValue);
    if (onSuggestionSelect) {
      onSuggestionSelect(suggestionValue);
    }
    setShowSuggestions(false);
    setHighlightedIndex(-1);
  };

  // Handle keyboard navigation
  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (mode === 'manual' && filteredSuggestions.length > 0) {
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        setShowSuggestions(true);
        setHighlightedIndex(prev => 
          prev < filteredSuggestions.length - 1 ? prev + 1 : prev
        );
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        setHighlightedIndex(prev => prev > 0 ? prev - 1 : -1);
      } else if (e.key === 'Enter' && highlightedIndex >= 0) {
        e.preventDefault();
        const selectedSuggestion = filteredSuggestions[highlightedIndex];
        handleSuggestionClick(selectedSuggestion.value);
      } else if (e.key === 'Escape') {
        setShowSuggestions(false);
        setHighlightedIndex(-1);
      }
    }
  };

  // Copy to clipboard functionality
  const handleCopy = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    e.stopPropagation();
    
    try {
      // Fallback method for better browser compatibility
      const textArea = document.createElement('textarea');
      textArea.value = autoGeneratedValue;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      document.execCommand('copy');
      textArea.remove();
      
      // Visual feedback
      const btn = e.currentTarget;
      const originalTitle = btn.title;
      btn.title = 'Copied!';
      btn.classList.add('bg-green-100');
      setTimeout(() => {
        btn.title = originalTitle;
        btn.classList.remove('bg-green-100');
      }, 1500);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Render text with highlighted match
  const renderHighlightedText = (text: string, searchTerm: string) => {
    const lowerText = text.toLowerCase();
    const lowerSearch = searchTerm.toLowerCase();
    const matchIndex = lowerText.indexOf(lowerSearch);

    if (matchIndex >= 0) {
      return (
        <>
          {text.substring(0, matchIndex)}
          <span className="font-semibold bg-yellow-100">
            {text.substring(matchIndex, matchIndex + searchTerm.length)}
          </span>
          {text.substring(matchIndex + searchTerm.length)}
        </>
      );
    }
    return text;
  };

  // Group suggestions by type
  const aiSuggestions = filteredSuggestions.filter(s => s.type === 'ai');
  const systemSuggestions = filteredSuggestions.filter(s => s.type === 'match');

  // Calculate default duplicate suggestions if not provided
  const defaultDuplicateSuggestions = duplicateSuggestions || {
    aiSuggestion: value ? `${value}-V2` : '',
    patternSuggestion: value.match(/^(.+?)[-_]?(\d+)$/) 
      ? value.replace(/(\d+)$/, (match) => String(parseInt(match) + 1).padStart(3, '0'))
      : `${value}-002`,
    aiConfidence: 95,
    patternConfidence: 92
  };

  return (
    <div className={className}>
      {/* Label and Radio Buttons Row */}
      <div className="flex items-center gap-3 mb-2">
        <label className="text-sm text-gray-700 whitespace-nowrap">
          {label} {required && <span className="text-red-500">*</span>}
        </label>
        <div className="flex items-center gap-4">
          {/* Auto Generate Radio */}
          <label className="flex items-center gap-1.5 cursor-pointer">
            <input
              type="radio"
              name="bundleCodeAllocation"
              value="auto"
              checked={mode === 'auto'}
              onChange={() => {
                onModeChange('auto');
                setShowSuggestions(false);
              }}
              disabled={disabled}
              className="w-4 h-4 text-[#5C1F3D] focus:ring-[#5C1F3D]"
            />
            <span className="text-sm text-gray-700">{autoModeLabel}</span>
          </label>
          
          {/* Manual Entry Radio */}
          <label className="flex items-center gap-1.5 cursor-pointer">
            <input
              type="radio"
              name="bundleCodeAllocation"
              value="manual"
              checked={mode === 'manual'}
              onChange={() => onModeChange('manual')}
              disabled={disabled}
              className="w-4 h-4 text-[#5C1F3D] focus:ring-[#5C1F3D]"
            />
            <span className="text-sm text-gray-700">{manualModeLabel}</span>
          </label>
        </div>
      </div>
      
      {/* Input Field with Autocomplete */}
      <div className="relative" ref={bundleCodeInputRef}>
        <div 
          className={mode === 'auto' ? 'pointer-events-none' : ''}
          style={mode === 'auto' ? { pointerEvents: 'none' } : {}}
        >
          <input
            type="text"
            placeholder={mode === 'auto' ? placeholder.auto : placeholder.manual}
            disabled={mode === 'auto' || disabled}
            value={mode === 'auto' ? autoGeneratedValue : value}
            onChange={(e) => {
              onChange(e.target.value);
              setShowSuggestions(true);
              setHighlightedIndex(-1);
            }}
            onKeyDown={handleKeyDown}
            onFocus={() => {
              if (mode === 'manual' && value.trim()) {
                setShowSuggestions(true);
              }
            }}
            className={`w-full px-3 py-2 border rounded-[3px] text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:border-transparent bg-white ${
              mode === 'manual' && isDuplicate
                ? 'border-red-500 focus:ring-red-500'
                : 'border-gray-300 focus:ring-[#5C1F3D]'
            } ${mode === 'auto' ? 'bg-gray-50 text-gray-500' : ''}`}
            style={{ height: '33px' }}
          />
        </div>
        
        {/* Copy Button - Only in Auto Mode */}
        {mode === 'auto' && autoGeneratedValue && (
          <button
            onClick={handleCopy}
            title="Copy Bundle Code"
            className="absolute right-2 top-1/2 -translate-y-1/2 p-1.5 hover:bg-gray-100 rounded transition-colors pointer-events-auto"
          >
            <svg 
              className="w-4 h-4 text-gray-600" 
              fill="none" 
              stroke="currentColor" 
              viewBox="0 0 24 24"
            >
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </button>
        )}
        
        {/* Autocomplete Suggestions Dropdown */}
        {mode === 'manual' && showSuggestions && filteredSuggestions.length > 0 && (
          <div className="absolute top-full left-0 right-0 mt-1 bg-white border border-gray-300 rounded-[3px] shadow-lg z-50 max-h-80 overflow-y-auto">
            {/* Duplicate Code Error Banner */}
            {isDuplicate && (
              <div className="px-3 py-2.5 bg-red-50 border-b border-red-200 flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <p className="text-xs text-red-800 font-medium">Bundle code already exists.</p>
                  <p className="text-xs text-red-600 mt-0.5">This bundle code is already allocated to another bundle in inventory.</p>
                </div>
              </div>
            )}
            
            {/* AI-Driven Suggestions Section */}
            {aiSuggestions.length > 0 && (
              <>
                <div className="px-3 py-1.5 text-xs font-medium text-purple-700 bg-purple-50 border-b border-purple-100 flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5" />
                  AI-driven suggestions
                </div>
                {aiSuggestions.map((suggestion, idx) => (
                  <div
                    key={`ai-${suggestion.value}-${idx}`}
                    onClick={() => handleSuggestionClick(suggestion.value)}
                    onMouseEnter={() => setHighlightedIndex(idx)}
                    className={`px-3 py-2.5 cursor-pointer transition-colors border-b border-gray-50 ${
                      highlightedIndex === idx ? 'bg-purple-50' : 'hover:bg-gray-50'
                    }`}
                  >
                    <div className="flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-purple-600 flex-shrink-0" />
                      <span className="text-sm text-gray-900 font-mono flex-1">
                        {renderHighlightedText(suggestion.value, value)}
                      </span>
                      {suggestion.reason && (
                        <span className="text-xs text-gray-500">{suggestion.reason}</span>
                      )}
                    </div>
                  </div>
                ))}
              </>
            )}
            
            {/* System-Defined Suggestions Section */}
            {systemSuggestions.length > 0 && (
              <>
                <div className="px-3 py-1.5 text-xs font-medium text-gray-500 bg-gray-50 border-b border-gray-100 flex items-center gap-1.5">
                  <AlignJustify className="w-3.5 h-3.5" />
                  System-Defined
                </div>
                {systemSuggestions.map((suggestion, idx) => {
                  const adjustedIdx = idx + aiSuggestions.length;
                  return (
                    <div
                      key={`system-${suggestion.value}-${idx}`}
                      onClick={() => handleSuggestionClick(suggestion.value)}
                      onMouseEnter={() => setHighlightedIndex(adjustedIdx)}
                      className={`px-3 py-2.5 cursor-pointer transition-colors border-b border-gray-50 last:border-b-0 ${
                        highlightedIndex === adjustedIdx ? 'bg-blue-50' : 'hover:bg-gray-50'
                      }`}
                    >
                      <div className="flex items-center gap-2">
                        <AlignJustify className="w-4 h-4 text-gray-400 flex-shrink-0" />
                        <span className="text-sm text-gray-900 font-mono flex-1">
                          {renderHighlightedText(suggestion.value, value)}
                        </span>
                        {suggestion.reason && (
                          <span className="text-xs text-gray-500">{suggestion.reason}</span>
                        )}
                      </div>
                    </div>
                  );
                })}
              </>
            )}
          </div>
        )}
      </div>
      
      {/* Error Message with Conflicting Code and Recommend Button */}
      {isDuplicate && mode === 'manual' && !showSuggestions && (
        <div className="mt-2 flex items-start gap-2">
          <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="text-xs text-red-600">
              This bundle code is already allocated to another bundle
            </p>
            {conflictingCode && (
              <div className="flex items-center gap-2 mt-1">
                <code className="text-xs font-mono text-red-700 bg-red-50 px-2 py-0.5 rounded">
                  {conflictingCode}
                </code>
                <button
                  onClick={() => setShowSuggestions(true)}
                  className="text-xs text-[#5C1F3D] hover:text-[#4a1831] underline font-medium"
                >
                  Recommend
                </button>
              </div>
            )}
          </div>
        </div>
      )}
      
      {/* AI-Powered Duplicate Code Warning with Smart Suggestions */}
      {isDuplicate && mode === 'manual' && (
        <div className="mt-2 p-3 bg-purple-50 border-l-4 border-[#5C1F3D] rounded-r-[3px]">
          <div className="flex items-start gap-2">
            <Sparkles className="w-4 h-4 text-[#5C1F3D] mt-0.5 flex-shrink-0" />
            <div className="flex-1">
              <p className="text-xs text-gray-900 mb-1">
                <span className="font-medium">Bundle code already exists.</span> This bundle code is already allocated to another bundle in the inventory.
              </p>
              <div className="mt-2">
                <p className="text-xs font-medium text-[#5C1F3D] mb-2">AI Suggestions</p>
                <div className="space-y-2">
                  {/* AI Suggestion */}
                  <div className="flex items-center gap-2">
                    <span className="px-1.5 py-0.5 text-xs rounded flex-shrink-0 bg-purple-100 text-purple-700 border border-purple-200">
                      AI
                    </span>
                    <span className="text-xs text-gray-600 flex-shrink-0">
                      {defaultDuplicateSuggestions.aiConfidence}%: Based on your naming pattern
                    </span>
                    <code className="flex-1 px-2 py-1 bg-white border border-gray-200 rounded text-xs font-mono text-gray-900">
                      {defaultDuplicateSuggestions.aiSuggestion}
                    </code>
                    <button
                      onClick={() => {
                        onChange(defaultDuplicateSuggestions.aiSuggestion);
                        setShowSuggestions(false);
                      }}
                      className="px-3 py-1 text-xs bg-[#5C1F3D] text-white rounded-[3px] hover:bg-[#4a1831] transition-colors whitespace-nowrap flex-shrink-0"
                    >
                      Use this
                    </button>
                  </div>
                  
                  {/* Pattern Suggestion */}
                  <div className="flex items-center gap-2">
                    <span className="px-1.5 py-0.5 text-xs rounded flex-shrink-0 bg-blue-100 text-blue-700 border border-blue-200">
                      Pattern
                    </span>
                    <span className="text-xs text-gray-600 flex-shrink-0">
                      {defaultDuplicateSuggestions.patternConfidence}%: Sequential numbering
                    </span>
                    <code className="flex-1 px-2 py-1 bg-white border border-gray-200 rounded text-xs font-mono text-gray-900">
                      {defaultDuplicateSuggestions.patternSuggestion}
                    </code>
                    <button
                      onClick={() => {
                        onChange(defaultDuplicateSuggestions.patternSuggestion);
                        setShowSuggestions(false);
                      }}
                      className="px-3 py-1 text-xs bg-[#5C1F3D] text-white rounded-[3px] hover:bg-[#4a1831] transition-colors whitespace-nowrap flex-shrink-0"
                    >
                      Use this
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}